# Generated by Django 5.1.3 on 2024-11-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.BigIntegerField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='exchange_da_symbol_452a6e_idx')],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
