# Generated by Django 5.1.3 on 2024-11-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancedata',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='binancedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
