# Generated by Django 5.1.3 on 2024-11-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_data', '0002_alter_binancedata_symbol_alter_binancedata_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='binancedata',
            unique_together={('symbol', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='binancedata',
            index=models.Index(fields=['symbol', 'timestamp'], name='exchange_da_symbol_452a6e_idx'),
        ),
    ]
